services:
  mongo:
    image: mongo:6.0.7
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
    - ./volume:/data/db
    ports:
    - 27017:27017

